feat: add url-filter pages
gdsc-hcmut/url-shortener-fe pull request #107
Opened 2023-06-27 14:45 UTC by trungtranquoc

- Add Url-filter page
- Add files svg 
- Add 1 remote to file App.js

2023-06-29 04:38 UTC, tomgermanyyyy requested changes

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +import AddToBlackList from 'assets/icons/add_to_blacklist.svg';
Về mấy cái icon svg tụi em nên đặt có đuôi "Icon" ở đằng sau cho dễ nhận biết, ví dụ AddToBlacklistIcon. Blacklist viết liền nhau nên nó nên là Blacklist chứ không phải BlackList nha 😉

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +import LeftArrow from 'assets/icons/left_arrow.svg';
"Icon"

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +import LimitDomain from 'assets/icons/limit_domain_icon.svg';
này nữa nè

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +import Rightarrow from 'assets/icons/right_arrow.svg';
RightArrow nha tụi em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +  const [search, setSearch] = useState('');
search là động từ, trong khi này là cái chuỗi em search, mình nên đặt tên biến là searchText nha em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +  const [modeAllUrl, setModeAllUrl] = useState(true);
em đặt lại tên biến này nha, này là biến boolean 😋

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +    console.log('MaxPage >>> ', maxPage);
log xong xem dữ liệu xong rồi thì xoá đi nha em 😇

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +                  fill="#0f9d58"
này hình như eslint nó báo lỗi nè, mình dùng fill của tailwind nha em 😋

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +                    fill="#4285F4"
này luôn 😋

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +                  onClick={() => DeleteUrl(url)}
tên hàm, tên biến mình đặt theo camelCase nhé em, đọc lại naming convention nha
```suggestion
                  onClick={() => deleteUrl(url)}
```

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +                    fill="#4285F4"
này luôn nè

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +                    fill="#4285F4"
sửa hết mấy chỗ fill này nha em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +  const [addLink, setAddLink] = useState([]);
nên đặt là `newLink` nha em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +  const [addOrg, setAddOrg] = useState([]);
này thì nên là `newOrg` nha em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +  const limit = 15;
xem lại này nha em, này là constant nè

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +  const AddingUrl = (newLink, newOrg) => {
tên hàm thì camelCase nè

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +  const DeleteUrl = (url) => {
đặt lại tên hàm nha em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +    const listUser = urls.filter((e) => e.id !== url.id);
listUser này là gì á em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/components/UrlFilter/index.jsx
> +          <div className="flex items-center justify-center w-[560px] border-r border-gray-500">
màu thì dùng màu theo design guideline nha em, trong figma url có cái bảng màu á, config màu vô file `tailwind.config.js` rồi xài nha em, chú ý naming convention luôn

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/pages/URLFilterPage.jsx
> +  const [toggleMenu, setToggleMenu] = useState(false);
đặt lại theo convention nha em

2023-06-29 04:38 UTC, tomgermanyyyy commented on src/pages/URLFilterPage.jsx
> +  const [getUrl, setGetUrl] = useState({});
biến này dùng làm gì vậy em 😅

2023-06-29 07:45 UTC, trungtranquoc commented on src/components/UrlFilter/index.jsx
> +    const listUser = urls.filter((e) => e.id !== url.id);
dạ listUser là cái để lọc (hash trên UI). Nữa có API thì em đổi chỗ đó thành gọi API xóa ạ

2023-06-29 07:47 UTC, trungtranquoc commented on src/pages/URLFilterPage.jsx
> +  const [getUrl, setGetUrl] = useState({});
Dạ biến đó dùng để hash số liệu (chuyển trang sang trang hiện information của Link với User). Trong tương lai có API thì em đổi trang đó thành trang riêng để call API ạ. Giờ làm tạm để viết UI trước ạ.

2023-07-01 14:47 UTC, lygioian commented on src/components/UrlFilter/index.jsx
> +                alt="right-arrow"
chỉnh theo convention nha em

2023-07-01 14:47 UTC, lygioian commented on src/components/UrlFilter/index.jsx
> +          placeholder="long-link"
placeholder kì vậy em

2023-07-01 14:47 UTC, lygioian commented on src/components/UrlFilter/index.jsx
> +          onClick={() => addingUrl(addLink, addOrg)}
```suggestion
          onClick={() => addUrl(addLink, addOrg)}
```

2023-07-02 05:44 UTC, tomgermanyyyy requested changes

2023-07-02 05:44 UTC, tomgermanyyyy commented on src/pages/URLInformationPage.jsx
> +import UserInformation from 'components/UserInformation';
phần này em nên tạo 1 file là `index.js` trong thư mục `components`, trong file đó import lại tất cả các component trong rồi export name ra để khi em dùng ở các pages thì khi import phải import đúng cái name, như vậy dễ kiểm soát code hơn
Reference: https://stackoverflow.com/questions/36790911/reexport-class-in-typescript

không hiểu thì hỏi lại anh nha

2023-07-02 05:44 UTC, tomgermanyyyy commented on src/pages/URLInformationPage.jsx
> +export default function URLInformationPage() {
sửa tên page lại cho phù hợp nha em

2023-07-02 05:44 UTC, tomgermanyyyy commented on src/pages/URLInformationPage.jsx
> +  const [toggleMenu, setToggleMenu] = useState(false);
sửa lại cho đúng convention biến boolean nè em 😁

2023-07-02 05:44 UTC, tomgermanyyyy commented on src/pages/URLInformationPage.jsx
> +              </div>
cục này tụi em tách thành 1 component luôn nha, component đó sẽ nhận hàm `fetchList` và `fetchDetail` vào từ mỗi page của tụi em, rồi`fetchList` sẽ truyền vô `<MyUrl />` và `fetchDetail` sẽ truyền vô `<Detail />` để xử lý. Phần này có gì không hiểu hỏi lại anh nha

2023-07-28 10:15 UTC, trungtranquoc commented on src/components/UrlFilter/index.jsx
> +];
dạ em có chỉnh cái đó rồi ạ. Phần Enum đó có viết bên constant nên em xài luôn

2023-07-28 10:15 UTC, trungtranquoc commented on src/components/UrlFilter/index.jsx
> +  const addingUrl = (newLink, newOrg) => {
Dạ phần này trong phần Mock Code cũ, giờ em có API nên bỏ phần đó rồi ạ

2023-07-29 09:15 UTC, trungtranquoc commented on src/App.jsx
> +          <Route path="/url-filter/:id" element={<URLInformationPage />} />
Dạ em đã xóa URLInformationPage và thêm Authentication vô URLFilter. Hiện tại chờ nhập code rồi thêm check Admin vô URlFilter nữa ạ.

2023-07-29 09:15 UTC, trungtranquoc commented on src/components/UrlFilter/index.jsx
> +          placeholder="long-link"
Dạ phần này em xóa rồi ạ, nó dùng để mock code

2023-07-29 09:16 UTC, trungtranquoc commented on src/components/UrlFilter/index.jsx
> +          onClick={() => addingUrl(addLink, addOrg)}
Dạ phần này em xóa rồi ạ.

2023-07-29 09:17 UTC, trungtranquoc commented on src/components/UserInformation/general/CreatedOn.jsx
> +        </span>
Dạ span để hiển thị á anh :v

2023-07-29 09:17 UTC, trungtranquoc commented on src/components/UserInformation/general/ExpireTime.jsx
> +  const [currTime, setCurrTime] = useState(new Date(expireTime));
Dạ phần này em delete UserInformation rồi ạ

2023-07-29 09:17 UTC, trungtranquoc commented on src/components/UserInformation/general/ExpireTime.jsx
> +          {/* )} */}
Em xóa file này rồi ạ

2023-07-29 09:17 UTC, trungtranquoc commented on src/components/UserInformation/general/ExpireTime.jsx
> +          </span> */}
Em xóa file này rồi ạ

2023-07-29 09:17 UTC, trungtranquoc commented on src/components/UserInformation/index.jsx
> +import AccountCircle from 'assets/icons/account_circle_white.svg';
Em xóa file này rồi ạ

2023-07-29 09:18 UTC, trungtranquoc commented on src/components/UserInformation/index.jsx
> +        <img src={CloseIcon} className="w-[24px] h-[24px]" alt="close-icon" />
Em xóa file này rồi ạ

2023-07-29 09:18 UTC, trungtranquoc commented on src/components/UserInformation/index.jsx
> +              anguyenvan@gmail.com
Em xóa file này rồi ạ

2023-07-29 09:18 UTC, trungtranquoc commented on src/pages/URLInformationPage.jsx
> +import UserInformation from 'components/UserInformation';
Em xóa file này rồi ạ

2023-07-29 09:18 UTC, trungtranquoc commented on src/pages/URLInformationPage.jsx
> +export default function URLInformationPage() {
Em xóa file này rồi ạ

2023-07-29 09:18 UTC, trungtranquoc commented on src/pages/URLInformationPage.jsx
> +  const [toggleMenu, setToggleMenu] = useState(false);
Em xóa file này rồi ạ

2023-07-29 09:18 UTC, trungtranquoc commented on src/pages/URLInformationPage.jsx
> +              </div>
Em xóa file này rồi ạ

2023-07-29 09:19 UTC, trungtranquoc commented on src/components/UrlFilter/index.jsx
> +                  <UrlRow url={url} deleteUrl={deleteUrl} />
Dạ em chỉnh nó thành addUrlToBlacklist rồi ạ.

2023-07-29 09:20 UTC, trungtranquoc commented on src/components/UrlFilter/index.jsx
> +                  <UrlRow url={url} deleteUrl={deleteUrl} />
Dạ em bỏ key trực tiếp vô trong luôn rồi ạ

2023-07-29 09:20 UTC, trungtranquoc commented on src/components/DetailV2/Chart.jsx
> +import {} from 'lodash';
Dạ file này em trích từ file cũ

2023-07-29 09:20 UTC, trungtranquoc commented on src/components/DetailV2/Chart.jsx
> +import { ReactComponent as ArrowDown } from 'assets/icons/arrow_down.svg';
Dạ code này em trích từ code cũ

2023-07-29 09:23 UTC, trungtranquoc commented on src/components/DetailV2/Chart.jsx
> +  const [option, setOption] = useState('Last Year');
Dạ file này em trích từ file cũ

2023-07-29 09:23 UTC, trungtranquoc commented on src/components/DetailV2/Chart.jsx
> +  const sortOptions = ['Last Year', 'Last Day', 'Last Week', 'Last Month'];
Dạ code này em trích từ code cũ

2023-07-29 09:23 UTC, trungtranquoc commented on src/components/DetailV2/Chart.jsx
> +              isOpen ? '' : 'hidden'
Dạ code này em trích từ code cũ

2023-07-29 10:10 UTC, tomgermanyyyy submitted a review, later dismissed

2023-07-29 10:20 UTC, merged