feat: add url-blacklist
gdsc-hcmut/url-shortener-fe pull request #108
Opened 2023-06-27 15:37 UTC by quochieu586

2023-06-29 05:44 UTC, tomgermanyyyy requested changes

2023-06-29 05:44 UTC, tomgermanyyyy commented on package-lock.json
xoá file này nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on yarn.lock
xoá file này luôn nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/App.jsx
> +            path="/urlblacklist"
cho dễ đọc cái url path thì mình dùng kebab case nha em 
```suggestion
            path="/url-blacklist"
```

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +export default function Urlblacklist() {
rename lại nha em
```suggestion
export default function UrlBlacklist() {
```

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [search, setSearch] = useState('');
này nên là `searchText` thì sẽ clear hơn

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [listuser, setListuser] = useState([]);
rename lại chỗ này nha em, nên là camelCase

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [addlink, setAddlink] = useState('');
camelCase luôn nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [datesearch, setDatesearch] = useState('');
camelCase luôn nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [deleteUrl, setDeleteUrl] = useState({});
tên biến nên bắt đầu là danh từ nha em, còn khi nào là tên hàm mình mới bắt đầu bằng động từ, `deleteUrl` khi dùng em sẽ dễ nhầm thành đây là một hàm đó 😁

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [deleteMode, setDeleteMode] = useState(false);
này là biến boolean, đặt lại tên nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [pageCount] = useState([1, 2, 3, 4]);
đặt lại tên biến theo convention array nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +        addedat: '20:30 - 17/06/2023',
đặt lại tên biến nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +        addedby: 'Tran Quoc Hieu',
đặt lại tên biến nha em

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const handleAdding = () => {
như này là oke rồi nha em
```suggestion
  const handleAdd = () => {
```

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +  const [listuser, setListuser] = useState([]);
mà cho anh hỏi ý nghĩa biến này là gì vậy em 😂

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +      const clearFormat = (num) => (num > 9 ? `${num}` : `0${num}`);
hàm này nên đặt là vầy nha em
```suggestion
      const formatNumber = (num) => (num > 9 ? `${num}` : `0${num}`);
```

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +      const newUser = {
tại sao biến này là `newUser` em nhỉ 🤔

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +      const formatsearch = e.target.value.split('-');
tên biến nên là danh từ nha em, `format` dùng như vậy là động từ á

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +)}/${clearFormat(current.getFullYear())}`,
đoạn này em nên tách thành một hàm `formatDateTime` rồi truyền cái current vô xử lý trong đó nha, như vậy dễ đọc code hơn

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/components/UrlBlacklist/index.jsx
> +    if (e.target.value === '') setDatesearch('');
anh thắc mắc là có dateSearch rồi sao lại còn có dateInput nữa nhỉ 🤔

2023-06-29 05:44 UTC, tomgermanyyyy commented on src/pages/UrlBlacklistPage.jsx
> +  const [toggleMenu, setToggleMenu] = useState(false);
đặt lại tên biến nha em

2023-06-29 08:22 UTC, quochieu586 commented on src/components/UrlBlacklist/index.jsx
> +  const [listuser, setListuser] = useState([]);
biến này để e hash số liệu á a :Đ

2023-07-02 07:50 UTC, tomgermanyyyy requested changes
lần này anh thấy có tiến bộ hơn rồi, code đã có style hơn, cơ mà còn một vài lỗi nhỏ cần fix thêm nhé 😁

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +import RightArrowIcon from '../../assets/icons/arrow_forward.svg';
tại sao cần '../../' đó vậy em

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +}) {
`listUser` với `pageList` ở đây mỗi cái có tác dụng gì vậy em
với các hàm xử lý sự kiện thì mình nên có prefix `on`, ví dụ `handleDelete` với `handleAdd` thì mình nên theo convention là `onDelete` với `onAdd` nha em

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +
chỗ này nếu người ta nhập input chữ hoa thì có search được hong em

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +  const tableList = () => (
table mà còn list là sao em :v

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +        {listUser
listUser ở đây có ý nghĩa gì em, anh đọc code thấy đây là danh sách url mà chứ đâu phải danh sách user

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +                    setDeletingUrl(item);
tại sao em lại cần `setDeletingUrl(item);` vậy

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +              removed from Blacklist
search **template literals** để clean cục code này hơn nha em

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +  const [addingLink, setAddingLink] = useState('');
sao em đặt tên là `addingLink` zậy bíe

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +        {listUser.filter((el) => checkSearch(el)).length}
xài template literals nha em

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +      {tableList()}
tại sao lại là gọi hàm `tableList` ở đây mà không phải là component vậy em

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +          <img src={LeftArrowIcon} alt="Previous" />
chú ý `alt` theo cùng 1 style nha em, anh thấy các `alt` của các `<img/>` em đang dùng mỗi cái 1 kiểu á 😆

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/DomainBlacklist/index.jsx
> +  const [listDomain, setListDomain] = useState([]);
`domainList` sẽ hợp lý về ngữ pháp hơn nha em 😅

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/DomainBlacklist/index.jsx
> +  const [pageArray] = useState([1, 2, 3, 4]);
này chưa đúng convention về array nè em

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/DomainBlacklist/index.jsx
> +  }/${time.getFullYear()} ${time.toLocaleTimeString()}`;
hàm này mình có thể xài nhiều chỗ, nên em bỏ vào thử mục `utils` rồi import vào đây xài nha

2023-07-02 07:50 UTC, tomgermanyyyy commented on src/components/DomainBlacklist/index.jsx
> +      const current = new Date();
current đây thì chưa rõ là current gì á em, có thể là current time, hoặc là current url đúng không em 😅

2023-07-03 13:19 UTC, quochieu586 commented on src/components/Blacklist/index.jsx
> +import RightArrowIcon from '../../assets/icons/arrow_forward.svg';
à dạ em chỉnh lại rồi ạ

2023-07-03 14:03 UTC, quochieu586 commented on src/components/DomainBlacklist/index.jsx
> +  }/${time.getFullYear()} ${time.toLocaleTimeString()}`;
cho em hỏi là mình tách ra như component luôn hay sao ạ, em chưa rành chỗ này lắm ạ :v

2023-07-03 14:34 UTC, quochieu586 commented on src/components/Blacklist/index.jsx
> +
dạ search đúng chữ mới được á a, cái này e thấy giống bên cái myUrl trên web của mình :v

2023-07-03 14:57 UTC, quochieu586 commented
Last updated: 
+ add DeleteLinkSnackbar
+ add SuccessSnackbar
+ add WarnSnackbar
+ add DeleteModalV2 (no Redux)
+ sửa logic pageList lại :v
+ em tách Add với Search ra ngoài component chính cho đúng logic :> 
![image](https://github.com/gdsc-hcmut/url-shortener-fe/assets/131350457/ab91eb84-65fe-4ce4-893a-8d9aaa60dc91)
![image](https://github.com/gdsc-hcmut/url-shortener-fe/assets/131350457/87ca0eb3-bf03-4d46-880f-a4dcb9e5311c)
![image](https://github.com/gdsc-hcmut/url-shortener-fe/assets/131350457/1660aabb-2f98-404d-850c-89a7c98b225a)

2023-07-03 14:57 UTC, quochieu586 commented
![image](https://github.com/gdsc-hcmut/url-shortener-fe/assets/131350457/e9202d62-f973-49ca-baa0-3d56c7504883)

2023-07-05 10:00 UTC, quochieu586 commented
Last upedated (7/5/2023): 
+ Thêm function formatDateTime
+ Chỉnh lại Responsive cho web :v
* Em chưa update lịch, với lại cái toastify em cũng chưa rõ cách config lắm :v

2023-07-26 04:13 UTC, tomgermanyyyy requested changes

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +  }, [dateInput]);
tách hàm ra utils

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +  const [datePicker, setDatePicker] = useState(false);
boolean

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +      </thead>
tách cục này thành 1 component

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +      <tbody>
tách nguyên cái `<tbody>` thành 1 component, dài quá em

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +                }}
tách thành 1 hàm rồi truyền vô thôi

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/Blacklist/index.jsx
> +              } border-[1px] border-solid
tách logic này ra ngoài, chỉ truyền biến vào className thôi

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/DomainBlacklist/index.jsx
> +    const list = [
có api rồi thì bỏ cái này đi em

2023-07-26 04:13 UTC, tomgermanyyyy commented on src/components/SnackbarV2/WarnSnackbar.jsx
SuccesSnackbar, DeleteLinkSnackbar, WarnSnackbar chỉ nên là 1 component Snackbar nhận props là `type` vào thôi, `type` đó là 1 cái enum cho 3 trường hợp, rồi trong Snackbar tụi em check để render ra icon tương ứng

2023-07-27 07:59 UTC, quochieu586 commented on src/components/DeleteModalV2/index.jsx
> +              title === 'Domain Blacklist' ? 'domain' : 'url'
Dạ em fix cái này rồi nha a

2023-07-27 08:13 UTC, quochieu586 commented on src/components/Blacklist/index.jsx
> +  const table = () => (
Dạ e fix xong cái này rồi

2023-07-27 08:15 UTC, quochieu586 commented on src/components/Blacklist/index.jsx
> +  const paginationBar = () => {
À cái này em tính để tạm vậy, mốt lúc merge code thì lấy component của Trung luôn, với cái này em cũng chưa chỉnh UI lại.

2023-07-27 08:21 UTC, quochieu586 commented on src/components/Blacklist/index.jsx
> +  }, [dateInput]);
Dạ em fix xong cái này rồi nha a

2023-07-27 08:23 UTC, quochieu586 commented on src/components/SnackbarV2/WarnSnackbar.jsx
À cái snackbar này tạm thời mình chưa có dùng tới, em có đổi qua xài với custom lại cái toastify rồi á anh.

2023-07-27 08:24 UTC, quochieu586 commented on src/components/DomainBlacklist/index.jsx
> +    const list = [
À dạ em fix rồi ạ

2023-07-27 08:39 UTC, quochieu586 commented on src/components/Blacklist/index.jsx
> +                }}
Dạ em fix cái này rồi ạ

2023-07-27 08:47 UTC, quochieu586 commented on src/components/Blacklist/index.jsx
> +              } border-[1px] border-solid
Dạ nếu tách ra em sợ hơi bị rối code á anh, do em ví dụ với cái này em chỉ xài mỗi chỗ này, không có tái sử dụng á anh.

2023-07-29 09:09 UTC, tomgermanyyyy requested changes

2023-07-29 09:09 UTC, tomgermanyyyy commented on src/components/SnackbarV2/index.jsx
> +const EnumState = {
```suggestion
const SnackbarType = {
```

2023-07-29 10:08 UTC, tomgermanyyyy approved these changes

2023-07-29 10:13 UTC, merged